description: Overlay your HTML with eye candy
keywords: javascript overlay,jquery lightbox,jquery applebox,jquery overlay,jquery overlayed content,applebox,apple box

group:
  title: Overlays
  slug: overlay
  children: 8