description: The second most important UI widget
keywords: tooltips, javascript tooltip, jquery tooltip, jquery tooltip plugin, javascript tooltips, jquery tooltips

group:
  title: Tooltips
  slug: tooltip
  children: 7