resources:
    index.html:
        index: 1
        title: Minimal setup for rangeinput
        description: HTML5 range input for humans
        keywords: HTML5 range input, jquery range, jquery rangeinput, javascript range input, skinnable rangeinput

